import { Router, Request, Response } from 'express';
import { collections } from '../db';

export const itemsRouter = Router();

// Define Item interface to match what we store in Firestore.
// The id will be a string generated by Firestore.
interface Item {
  id: string;
  name: string;
  description: string;
  createdAt: string;
}

// GET /api/items - Fetch all items from Firestore
itemsRouter.get('/', async (_req: Request, res: Response) => {
  try {
    const snapshot = await collections.items.orderBy('createdAt', 'asc').get();
    const items: Item[] = [];
    
    snapshot.forEach((doc) => {
      const data = doc.data();
      items.push({
        id: doc.id,
        name: data.name,
        description: data.description,
        createdAt: data.createdAt,
      });
    });

    res.json({ items, total: items.length });
  } catch (error) {
    console.error('Error fetching items from Firestore:', error);
    res.status(500).json({ error: 'Failed to fetch items' });
  }
});

// GET /api/items/:id - Fetch a single item
itemsRouter.get('/:id', async (req: Request, res: Response) => {
  try {
    const doc = await collections.items.doc(req.params.id).get();
    
    if (!doc.exists) {
      res.status(404).json({ error: 'Item not found' });
      return;
    }

    const data = doc.data()!;
    res.json({
      id: doc.id,
      name: data.name,
      description: data.description,
      createdAt: data.createdAt,
    });
  } catch (error) {
    console.error('Error fetching item:', error);
    res.status(500).json({ error: 'Failed to fetch item' });
  }
});

// POST /api/items - Create a new item
itemsRouter.post('/', async (req: Request, res: Response) => {
  try {
    const { name, description } = req.body as { name?: string; description?: string };
    
    if (!name || !description) {
      res.status(400).json({ error: 'name and description are required' });
      return;
    }

    const newItemData = {
      name,
      description,
      createdAt: new Date().toISOString(),
    };

    // Add a new document with a generated id
    const docRef = await collections.items.add(newItemData);
    
    res.status(201).json({
      id: docRef.id,
      ...newItemData,
    });
  } catch (error) {
    console.error('Error creating item:', error);
    res.status(500).json({ error: 'Failed to create item' });
  }
});

// DELETE /api/items/:id - Delete an item
itemsRouter.delete('/:id', async (req: Request, res: Response) => {
  try {
    const docRef = collections.items.doc(req.params.id);
    const doc = await docRef.get();

    if (!doc.exists) {
      res.status(404).json({ error: 'Item not found' });
      return;
    }

    // Capture data before deletion to return it
    const data = doc.data()!;
    const itemToDelete = {
      id: doc.id,
      name: data.name,
      description: data.description,
      createdAt: data.createdAt,
    };

    await docRef.delete();
    
    res.json({ message: 'Item deleted', item: itemToDelete });
  } catch (error) {
    console.error('Error deleting item:', error);
    res.status(500).json({ error: 'Failed to delete item' });
  }
});
